# Generated by Django 5.0.6 on 2024-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_category_options_alter_dinnerplatters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=500),
        ),
    ]
